language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit
install:
  - composer install --no-interaction
script:
  - ./vendor/bin/phpunit
notifications:
  email: false
